main: su.nightexpress.goldenenchants.GoldenEnchants
version: 2.10.1
name: GoldenEnchants
author: NightExpress
desciption: Vanilla-like enchants for your server.
depend: [NexEngine]
api-version: 1.14
load: STARTUP